Devise auth
codeforUV/food_resources pull request #38
Opened 2020-10-21 20:33 UTC by bthooper

Devise added.

I am not sure this does all that we need at the moment, but the basics are there- a user model, registration and login. We need to connect the "forgot password" feature to an email service.

Also, we now need to connect users to food resources. I assume this is a users have_many food resources and a food resource belongs_to one user?  That will be a new branch, so I wanted to go ahead and submit this with the devise functionality.

2020-10-22 16:04 UTC, thomascchen commented
Thanks @bthooper! This all sounds right. Will try to take a look at this PR asap

2020-10-28 01:23 UTC, thomascchen requested changes
This is great! I think there's a few files we can remove. We can figure out an email service later. I'll add an issue for it. I think we might have some AWS credits sponsored by Code for America that we could use maybe.

I agree the next would be to establish a user have_many food resources relationship. 👍

2020-10-28 01:23 UTC, thomascchen commented on test/models/user_test.rb
> +  # test "the truth" do
We can leave this as is for now. I'd love to add [rspec](https://github.com/rspec/rspec-rails) sometime.

2020-10-28 01:23 UTC, thomascchen commented on app/controllers/users/confirmations_controller.rb
> +class Users::ConfirmationsController < Devise::ConfirmationsController
I don't think we need the confirmable module. We can probably delete this file.

2020-10-28 01:23 UTC, thomascchen commented on app/controllers/users/omniauth_callbacks_controller.rb
> +class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
Same here, I don't think we need this. Can delete.

2020-10-28 01:23 UTC, thomascchen commented on app/controllers/users/unlocks_controller.rb
> +class Users::UnlocksController < Devise::UnlocksController
Not sure we really need the lockable module either. I'd remove this.

2020-10-28 01:23 UTC, thomascchen commented on db/migrate/20201020183830_devise_create_users.rb
> +      ## Confirmable
Oh yea confirmable and lockable stuff is commented out here, so yea we don't need those associated controllers.

2020-10-28 13:43 UTC, bthooper commented
So, i deleted the unneeded controllers and pushed my commit up to my fork....but being a git novice, how do i get my commit to show up in this pull request? My googling research suggested that all I need to do is commit my changes....Heck, it even says "add more commits by pushing to the devise_auth branch on bthooper/food_resources' right above..and i did...and it shows in my repo...but why not here? am I missing something???

2020-10-28 14:00 UTC, thomascchen approved these changes
awesome!

2020-10-28 14:00 UTC, merged