#66 Update nokogiri gem to 1.11.0
codeforUV/food_resources pull request #69
Opened 2021-02-01 01:09 UTC by siobhanjacobson

To patch the security vulnerability listed here:

https://github.com/codeforUV/food_resources/security/dependabot/Gemfile.lock/nokogiri/open

I ended up updating a bunch of other gems, too.  I tested things out a bit locally and everything seems to be working fine.  Feel free to check out and test locally to verify!

2021-02-03 03:25 UTC, thomascchen requested changes
Thanks for tackling this! Rather than adding nokogiri to our Gemfile, I think we can just update it in our Gemfile.lock by doing `bundle update nokogiri` since it appears to only be used as a dependency of some of our dependencies. Actually, we might just go ahead and run `bundle update` to update all of our dependency tree. I *think* that would be fairly safe to do since we haven't gotten very complex in this app yet.

2021-02-05 02:52 UTC, siobhanjacobson commented
@thomascchen That makes more sense!  I've made that change.

2021-02-06 17:09 UTC, thomascchen approved these changes

2021-02-06 17:09 UTC, thomascchen commented
thanks!

2021-02-06 17:09 UTC, merged